name: code_viewer
description: This is a minimalist code-viewer with a copy button. It is mainly to view Dart code but will be able to highlight other languages in the future and with your help.
version: 0.0.2
homepage: https://github.com/kerby1998/code_viewer
repository: https://github.com/kerby1998/code_viewer

screenshots:
  - description: 'This screenshot shows an example of the code viewer in a smartphone'
    path: lib/assets/screenshot1.png

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


